scoreboard:
  bottom_text: "&9 /discord to join our discord"
  balance: "&7Silver: "
  balance: "&5Dark Quartz: "
  level: "&7Level: "
  time_based:
    separator:
      sun_rise: "&e ——————— &6&l☀ &e——————— "
      day: "&e ——————— &6&l☀ &e——————— "
      sun_set: "&b ——————— &9&l☽ &b——————— "
      night: "&b ——————— &9&l☽ &b——————— "
    title:
      sun_rise: "&7 >> &e&lOrb&6&lRPG &7<<"
      day: "&7 >> &e&lOrb&6&lRPG &7<<"
      sun_set: "&7 >> &b&lOrb&9&lRPG &7<<"
      night: "&7 >> &b&lOrb&9&lRPG &7<<"
messages:
  level_up: "&6Level up! &e%player% &3leveled up from &8%old_level% &3» &bLevel %level%"
  quest_item: "&7[&4&l!&7] You can't drop this item! You will need it in the future!"
  player_death: "&7[&4&l!&7] You died!"
  block_level_requirement: "&7[&4&l!&7] You need to be over &a%level%&7 to break this block!"
texts:
  damage_indicator: "&4%damage%❤"
guis:
  close_button: close_button # This ID is from the item file
  menu:
    title: "&eMenu"
command_messages:
  other:
    discord_hover: "&9Join our discord server!"
  errors:
    no_permission: "&7[&4&l!&7] You don't have the right permissions to use this command!"
    not_enough_arguments: "&7[&4&l!&7] You are missing one or more arguments that are required to execute this command!"
    incorrect_sender: "&7[&4&l!&7] You can't run this command!"
    incorrect_item: "&7[&4&l!&7] This item does not exist!"
    incorrect_argument: "&7[&4&l!&7] You need to enter a valid argument!"
  success:
    item_received: "&7[&a&l!&7] You received an item!"
    reload_complete: "&7[&a&l!&7] Reload complete!"
    warp_set: "&7[&a&l!&7] You have set %warp_name% to your current location!"
  info:
    item_info: "&7[&e&l!&7] The creator of this item is &a%creator% &7and their discord is &b%creator_discord%&7!"
    play_time:
      no_target: "&7[&e&l!&7] You have played %time% of OrbRPG"
      set_target: "&7[&e&l!&7] %target% has played %time% of OrbRPG"
rarities:
  default:
    lore: "&7&lDEFAULT"
    color_id: "&7"
  common:
    lore: "&7&lCOMMON"
    color_id: "&7"
  uncommon:
    lore: "&a&lUNCOMMON"
    color_id: "&a"
  rare:
    lore: "&9&lRARE"
    color_id: "&9"
  epic:
    lore: "&5&lEPIC"
    color_id: "&5"
  legendary:
    lore: "&6&lLEGENDARY"
    color_id: "&6"
  special:
    lore: "&d&lSPECIAL"
    color_id: "&5&l"
  menu:
    lore: "&eClick to open!"
    color_id: "&e"